### ISSUE TITLE
Confusion about `generate_roidb_training.py`

### ISSUE THREAD

**Issue by tracer9** [VisionLearningGroup/R-C3D#2]
Hi! When I read the code in `generate_roidb_training.py`, I found something weird. 
![image](https://user-images.githubusercontent.com/6302380/33703796-a16ba09c-db64-11e7-966d-7acf5ba8e373.png)
According to this part, the `WINS` should be a list contains only one element: 768*8

![image](https://user-images.githubusercontent.com/6302380/33703811-ae2713c0-db64-11e7-9c57-e68b95b7db5b.png)
According to this part, if `start` = 0, then `end` = 768*8, then `start` and `end` would be written into roidb:
![image](https://user-images.githubusercontent.com/6302380/33703904-1866df68-db65-11e7-802e-1743ee9a887b.png)

While in `minibatch.py`, the code create the data according to this `start` and `end`:
![image](https://user-images.githubusercontent.com/6302380/33704000-8286ea50-db65-11e7-8377-bcbd7e45c8e4.png)

However, the video size is `3x512x112x112` according to `cfg.TRAIN.LENGTH = (512, )`
![image](https://user-images.githubusercontent.com/6302380/33704135-1e09cd6c-db66-11e7-88a8-436b964cb3f0.png)

Is there anything wrong since 512 definitely less than 768 * 8?

**Comment by huijuan88** [comment]
512 is default value. New value 768 is overwritten in td_cnn_end2end.yml<https://github.com/VisionLearningGroup/R-C3D/blob/master/experiments/activitynet/td_cnn_end2end.yml>.

# in minibatch.py
# for idx in xrange(video_info[1], video_info[2], video_info[3]):

This line indicates that load images every video_info[3] frames.

So 768*8, load every 8 frames, means finally load 768 frames.




On Dec 7, 2017, at 02:50, Li Bin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! When I read the code in generate_roidb_training.py, I found something weird.
[image]<https://user-images.githubusercontent.com/6302380/33703796-a16ba09c-db64-11e7-966d-7acf5ba8e373.png>
According to this part, the WINS should be a list contains only one element: 768*8

[image]<https://user-images.githubusercontent.com/6302380/33703811-ae2713c0-db64-11e7-9c57-e68b95b7db5b.png>
According to this part, if start = 0, then end = 768*8, then start and end would be written into roidb:
[image]<https://user-images.githubusercontent.com/6302380/33703904-1866df68-db65-11e7-802e-1743ee9a887b.png>

While in minibatch.py, the code create the data according to this start and end:
[image]<https://user-images.githubusercontent.com/6302380/33704000-8286ea50-db65-11e7-8377-bcbd7e45c8e4.png>

However, the video size is 3x512x112x112 according to cfg.TRAIN.LENGTH = (512, )
[image]<https://user-images.githubusercontent.com/6302380/33704135-1e09cd6c-db66-11e7-88a8-436b964cb3f0.png>

Is there anything wrong since 512 definitely less than 768 * 8?

**Comment by tracer9** [comment]
Thanks a lot! I didn't notice that configure file `td_cnn_end2end.yml`.
