### ISSUE TITLE
missing filter_roidb

### ISSUE THREAD

**Issue by likelyzhao** [VisionLearningGroup/R-C3D#6]
hi in the training code filter_roidb is usd but no such module is imported 
where could I find this function?

**Comment by huijuan88** [comment]
filter_roidb is useless. You can ignore this.

On Dec 20, 2017, at 10:55, Zhijian <notifications@github.com<mailto:notifications@github.com>> wrote:


hi in the training code filter_roidb is usd but no such module is imported
where could I find this function?

**Comment by dansuthar** [comment]
@likelyzhao Looks like since most of the code was adopted from Faster-RCNN, there is where the filter_roidb function exists. You can look at https://github.com/rbgirshick/py-faster-rcnn/blob/96dc9f1dea3087474d6da5a98879072901ee9bf9/lib/fast_rcnn/train.py#L130

It is not actually doing any good in R-C3D's case. The code in this repo seems old and not updated to cancel out that line.

**Comment by likelyzhao** [comment]
@dansuthar thanks 
I just uncomment this line ....
